---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: tls-secret
    files:
      - example-do-not-use-in-prod-rootca.crt
      - example-do-not-use-in-prod-key.pem
