---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: provider
  namespace: default
spec:
  interval: 2m
  path: "./kubernetes/resources/provider"
  prune: true
  force: true
  retryInterval: 20s
  targetNamespace: default
  wait: true
  sourceRef:
    kind: GitRepository
    name: nativelink
    namespace: default
  dependsOn:
    - name: nativelink-tekton-resources
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nativelink-tekton-resources
  namespace: default
spec:
  interval: 2m
  path: "./kubernetes/resources/tekton"
  prune: true
  force: true
  retryInterval: 20s
  targetNamespace: default
  wait: true
  sourceRef:
    kind: GitRepository
    name: nativelink
    namespace: default
