---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -core

resources:
  - ../../resources/alert-kustomization

components:
  - ../../components/kustomization

replacements:
  - source:
      kind: Kustomization
      name: nativelink
      fieldPath: metadata.name
    targets:
      - select:
          kind: Kustomization
          name: nativelink-alert
        fieldPaths:
          - spec.postBuild.substitute.PLACEHOLDER_CONFIG_MAP_NAME
      - select:
          kind: Kustomization
          name: nativelink
        fieldPaths:
          - spec.postBuild.substituteFrom.0.name

patches:
- patch: |-
    - op: replace
      path: /spec/postBuild/substitute/PLACEHOLDER_FLAKE_OUTPUT
      value: github:TraceMachina/nativelink#image
    - op: add
      path: /spec/nameSuffix
      value: -core
  target:
    kind: Kustomization
    name: nativelink-alert
- patch: |-
    - op: replace
      path: /spec/path
      value: ./kubernetes/nativelink
    - op: add
      path: /spec/images
      value:
      - name: nativelink
        newName: localhost:5001/nativelink
        newTag: ${NATIVELINK_TAG}
  target:
    kind: Kustomization
    name: nativelink
