---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -lre-rs

components:
- ../../components/worker

patches:
- path: worker-lre-rs.yaml
  target:
    kind: Deployment
    name: nativelink-worker

images:
- name: nativelink-worker
  newName: nativelink-worker-lre-rs
