apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../kubernetes/resources/flux
- ../../kubernetes/resources/nativelink-core
- ../../kubernetes/resources/gateway-routes
- ../../kubernetes/workers/resources/worker-init
- ../../kubernetes/workers/resources/lre-cc
