---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nativelink.yaml
  - ../resources/insecure-certs

configMapGenerator:
  - name: nativelink-config
    files:
      - nativelink-config.json5
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled

images:
  - name: nativelink
